In [1]:
import pandas as pd
import sqlite3 as sql

In [2]:
conn = sql.connect('factbook.db')
conn

In [3]:
def sql_query(q):
    return pd.read_sql_query(q,conn)

In [4]:
q = 'select * from sqlite_master'
q

'select * from sqlite_master'

### **Check table**

In [14]:
q = 'select * from sqlite_master'
sql_query(q)

,type,name,tbl_name,rootpage,sql
0,table,sqlite_sequence,sqlite_sequence,3,"CREATE TABLE sqlite_sequence(name,seq)"
1,table,facts,facts,47,"CREATE TABLE ""facts"" (""id"" INTEGER PRIMARY KEY..."
2,table,cities,cities,2,CREATE TABLE cities (\n id integer prim...

### **Check table info**

In [15]:
q = "pragma table_info(sqlite_sequence)"
sql_query(q)

   cid  name type  notnull dflt_value  pk
0    0  name             0       None   0
1    1   seq             0       None   0

In [16]:
q = "pragma table_info(facts)"
sql_query(q)

    cid               name          type  notnull dflt_value  pk
0     0                 id       INTEGER        1       None   1
1     1               code  varchar(255)        1       None   0
2     2               name  varchar(255)        1       None   0
3     3               area       INTEGER        0       None   0
4     4          area_land       INTEGER        0       None   0
5     5         area_water       INTEGER        0       None   0
6     6         population       INTEGER        0       None   0
7     7  population_growth         float        0       None   0
8     8         birth_rate         float        0       None   0
9     9         death_rate         float        0       None   0
10   10     migration_rate         float        0       None   0

In [17]:
q = "pragma table_info(cities)"
sql_query(q)

   cid        name     type  notnull dflt_value  pk
0    0          id  INTEGER        0       None   1
1    1        name     TEXT        0       None   0
2    2  population  INTEGER        0       None   0
3    3     capital     bool        0       None   0
4    4    facts_id     TEXT        0       None   0

### **Show all data from facts table**

In [18]:
q = 'select * from facts'
sql_query(q)

,id,code,name,area,area_land,area_water,population,population_growth,birth_rate,death_rate,migration_rate
0,1,af,Afghanistan,652230.0,652230.0,0.0,3.256434e+07,2.32,38.57,13.89,1.51
1,2,al,Albania,28748.0,27398.0,1350.0,3.029278e+06,0.30,12.92,6.58,3.30
2,3,ag,Algeria,2381741.0,2381741.0,0.0,3.954217e+07,1.84,23.67,4.31,0.92
3,4,an,Andorra,468.0,468.0,0.0,8.558000e+04,0.12,8.13,6.96,0.00
4,5,ao,Angola,1246700.0,1246700.0,0.0,1.962535e+07,2.78,38.78,11.49,0.46
...,...,...,...,...,...,...,...,...,...,...,...
256,257,zh,Atlantic Ocean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
257,258,xo,Indian Ocean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
258,259,zn,Pacific Ocean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
259,260,oo,Southern Ocean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
260,261,xx,World,NaN,NaN,NaN,7.256490e+09,1.08,18.60,7.80,NaN

### **Show all data from cities table**

In [19]:
'select * from cities'

'select * from cities'

In [20]:
pd.read_sql_query('select * from cities',conn)

      id          name  population  capital facts_id
0      1    Oranjestad       37000        1      216
1      2  Saint John'S       27000        1        6
2      3     Abu Dhabi      942000        1      184
3      4         Dubai     1978000        0      184
4      5       Sharjah      983000        0      184
..   ...           ...         ...      ...      ...
392  393       Mbabane       66000        1      167
393  394         Sanaa     2419000        1      193
394  395          Aden      784000        0      193
395  396        Lusaka     1802000        1      194
396  397        Harare     1542000        1      195

[397 rows x 5 columns]

### **Show all data from facts table where name == Pakistan**

In [5]:
q = """select * from facts
   where name =='Pakistan'

"""
sql_query(q)

,id,code,name,area,area_land,area_water,population,population_growth,birth_rate,death_rate,migration_rate
0,132,pk,Pakistan,796095,770875,25220,199085847,1.46,22.58,6.49,1.54

In [6]:
q = """select * from cities
    where facts_id == 132

"""
sql_query(q)

    id        name  population  capital facts_id
0  273     Karachi    13876000        0      132
1  274      Lahore     7566000        0      132
2  275  Faisalabad     3038000        0      132
3  276  Rawalpindi     2164000        0      132
4  277      Multan     1775000        0      132
5  278   Islamabad      919000        1      132

### **Retrieve all rows where there is a matching record in both the facts and cities tables, using the id column in the facts table and the facts_id column in the cities table as the join condition.**

In [7]:
q = """select * from facts f
       inner join cities c
       on
       f.id == c.facts_id
    

"""
sql_query(q)

,id,code,name,area,area_land,area_water,population,population_growth,birth_rate,death_rate,migration_rate,id,name,population,capital,facts_id
0,216,aa,Aruba,180.0,180.0,0.0,112162,1.33,12.56,8.18,8.92,1,Oranjestad,37000,1,216
1,6,ac,Antigua and Barbuda,442.0,442.0,0.0,92436,1.24,15.85,5.69,2.21,2,Saint John'S,27000,1,6
2,184,ae,United Arab Emirates,83600.0,83600.0,0.0,5779760,2.58,15.43,1.97,12.36,3,Abu Dhabi,942000,1,184
3,184,ae,United Arab Emirates,83600.0,83600.0,0.0,5779760,2.58,15.43,1.97,12.36,4,Dubai,1978000,0,184
4,184,ae,United Arab Emirates,83600.0,83600.0,0.0,5779760,2.58,15.43,1.97,12.36,5,Sharjah,983000,0,184
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
392,167,wz,Swaziland,17364.0,17204.0,160.0,1435613,1.11,24.67,13.56,0.00,393,Mbabane,66000,1,167
393,193,ym,Yemen,527968.0,527968.0,0.0,26737317,2.47,29.98,6.28,1.00,394,Sanaa,2419000,1,193
394,193,ym,Yemen,527968.0,527968.0,0.0,26737317,2.47,29.98,6.28,1.00,395,Aden,784000,0,193
395,194,za,Zambia,752618.0,743398.0,9220.0,15066266,2.88,42.13,12.67,0.68,396,Lusaka,1802000,1,194
396,195,zi,Zimbabwe,390757.0,386847.0,3910.0,14229541,2.21,32.26,10.13,0.00,397,Harare,1542000,1,195

### **Show the country name and city name for entries where the country is 'Pakistan'**

In [8]:
q = """select f.name Country_name, c.name City from facts f
       inner join cities c
       on
       f.id == c.facts_id
       where f.name == "Pakistan" 
    

"""
sql_query(q)

  Country_name        City
0     Pakistan     Karachi
1     Pakistan      Lahore
2     Pakistan  Faisalabad
3     Pakistan  Rawalpindi
4     Pakistan      Multan
5     Pakistan   Islamabad

### **find countries that do not have any cities listed in the cities table. The query should return the country name and city name.**

In [21]:
q = """select f.name Country_name, c.name City_name  from facts f
        left join cities c
        on 
        f.id == c.facts_id
        where c.name is null

"""
sql_query(q)

                                     Country_name City_name
0                                          Kosovo      None
1                                          Monaco      None
2                                           Nauru      None
3                                      San Marino      None
4                                       Singapore      None
5                         Holy See (Vatican City)      None
6                                          Taiwan      None
7                                  European Union      None
8                     Ashmore and Cartier Islands      None
9                                Christmas Island      None
10                        Cocos (Keeling) Islands      None
11                              Coral Sea Islands      None
12              Heard Island and McDonald Islands      None
13                                 Norfolk Island      None
14                                      Hong Kong      None
15                                          Macau      None
16                              Clipperton Island      None
17            French Southern and Antarctic Lands      None
18                               Saint Barthelemy      None
19                                   Saint Martin      None
20                                        Curacao      None
21                                   Sint Maarten      None
22                                   Cook Islands      None
23                                           Niue      None
24                                        Tokelau      None
25                                  Bouvet Island      None
26                                      Jan Mayen      None
27                                       Svalbard      None
28                                       Akrotiri      None
29                 British Indian Ocean Territory      None
30                                       Dhekelia      None
31                                      Gibraltar      None
32                                       Guernsey      None
33                                         Jersey      None
34                                     Montserrat      None
35                               Pitcairn Islands      None
36       South Georgia and South Sandwich Islands      None
37                                 Navassa Island      None
38                                    Wake Island      None
39  United States Pacific Island Wildlife Refuges      None
40                                     Antarctica      None
41                                     Gaza Strip      None
42                                Paracel Islands      None
43                                Spratly Islands      None
44                                      West Bank      None
45                                   Arctic Ocean      None
46                                 Atlantic Ocean      None
47                                   Indian Ocean      None
48                                  Pacific Ocean      None
49                                 Southern Ocean      None
50                                          World      None

In [10]:
q = """select f.name AS Country_name,
              c.name AS City
       from cities c
       right join facts f
       on
       f.id = c.facts_id
       where c.id is null
"""

sql_query(q)

                                     Country_name  City
0                                          Kosovo  None
1                                          Monaco  None
2                                           Nauru  None
3                                      San Marino  None
4                                       Singapore  None
5                         Holy See (Vatican City)  None
6                                          Taiwan  None
7                                  European Union  None
8                     Ashmore and Cartier Islands  None
9                                Christmas Island  None
10                        Cocos (Keeling) Islands  None
11                              Coral Sea Islands  None
12              Heard Island and McDonald Islands  None
13                                 Norfolk Island  None
14                                      Hong Kong  None
15                                          Macau  None
16                              Clipperton Island  None
17            French Southern and Antarctic Lands  None
18                               Saint Barthelemy  None
19                                   Saint Martin  None
20                                        Curacao  None
21                                   Sint Maarten  None
22                                   Cook Islands  None
23                                           Niue  None
24                                        Tokelau  None
25                                  Bouvet Island  None
26                                      Jan Mayen  None
27                                       Svalbard  None
28                                       Akrotiri  None
29                 British Indian Ocean Territory  None
30                                       Dhekelia  None
31                                      Gibraltar  None
32                                       Guernsey  None
33                                         Jersey  None
34                                     Montserrat  None
35                               Pitcairn Islands  None
36       South Georgia and South Sandwich Islands  None
37                                 Navassa Island  None
38                                    Wake Island  None
39  United States Pacific Island Wildlife Refuges  None
40                                     Antarctica  None
41                                     Gaza Strip  None
42                                Paracel Islands  None
43                                Spratly Islands  None
44                                      West Bank  None
45                                   Arctic Ocean  None
46                                 Atlantic Ocean  None
47                                   Indian Ocean  None
48                                  Pacific Ocean  None
49                                 Southern Ocean  None
50                                          World  None

In [24]:
q = """Select f.name Country_name, c.name City_name, c.population City_population
        from facts f
        inner join cities c
        on 
        f.id == facts_id
        where c.capital == 1 and c.population > 10000000
        


"""
sql_query(q)

  Country_name     City_name  City_population
0    Argentina  Buenos Aires         13528000
1   Bangladesh         Dhaka         15391000
2        China       Beijing         15594000
3        Egypt         Cairo         11169000
4        India     New Delhi         22654000
5        Japan         Tokyo         37217000
6       Mexico   Mexico City         20446000
7  Philippines        Manila         11862000
8       Russia        Moscow         11621000

### **Show the country name and city name for entries where the country is 'United Arab Emirates'**

In [12]:
q = """select f.name Country_name, c.name City from facts f
       inner join cities c
       on
       f.id == c.facts_id
       where f.name == "United Arab Emirates" 
    

"""
sql_query(q)

           Country_name       City
0  United Arab Emirates  Abu Dhabi
1  United Arab Emirates      Dubai
2  United Arab Emirates    Sharjah

###  **Show Countryname Top 3 cities population Where capital == 0 and population > 10000000**

In [23]:
q = """select f.name Country_name, c.name City_name, c.population City_population  from facts f
        inner join cities c
        on
        f.id == c.facts_id
        where c.population > 10000000 and c.capital == 0
        order by 3 desc limit 3

"""
sql_query(q)

    Country_name        City_name  City_population
0  United States  New York-Newark         20352000
1          China         Shanghai         20208000
2         Brazil        Sao Paulo         19924000